<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <MonoGameContentReference Include="Content\Helicopter.mgcb" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="nkast.Wasm.Dom" Version="8.0.2" />
    <PackageReference Include="nkast.Xna.Framework" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Graphics" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Audio" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Media" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Input" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Game" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Content.Pipeline.Builder" Version="3.14.9001" />
  </ItemGroup>
</Project>
