<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Helicopter.Core\Helicopter.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <!-- Kni Blazor Backend -->
    <PackageReference Include="nkast.Xna.Framework.Content.Pipeline.Builder" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Blazor" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Graphics" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Audio" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Media" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Input" Version="3.14.9001" />
    <PackageReference Include="nkast.Xna.Framework.Game" Version="3.14.9001" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
