<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-browser</TargetFramework>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Helicopter.Core\Helicopter.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
  </ItemGroup>
</Project>
